name: Publish to pub.dev

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate package
        run: dart pub publish --dry-run

      - name: Publish
        run: dart pub publish --force
